### ISSUE TITLE
[BUG] - Uitlijning action-group niet ok

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-action-group#26]
**Omschrijf het probleem**
De uitlijning rechts vs links is niet consequent (spatie tussen de knoppen links).

**Screenshots**

![Schermafbeelding 2019-06-20 om 17 46 21](https://user-images.githubusercontent.com/1628243/64425135-39d8b800-d0ab-11e9-8a36-e246cee40880.png)

**Comment by cambiph** [comment]
Tom Coemans added a comment - 02/Aug/19 6:07 PM

>Probleem stelt zich ook bij de Webuniversum component, ik zal dit oplossen en PR maken bij Webuniversum.

Tom Coemans added a comment - 03/Aug/19 9:09 AM

>PR aangemaakt bij Webuniversum.

Tom Coemans added a comment - 05/Aug/19 11:10 AM - edited

>PR declined, er bestaan blijkbaar mod attributen (mod-collapse-*) zoals bijvoorbeeld mod-collapse-xs die ervoor zorgen dat op kleine schermen de buttons als block elementen getoond worden. Deze attributen waren niet gedocumenteerd en zullen binnenkort aangevuld worden op de documentatie website.

>De vl-ui-action-group kan dus best uitgebreid worden met de mod attributen om deze bug op te lossen. Best ook een default voorzien zodat het standaard geen probleem geeft op een klein scherm.

**Comment by coemans** [comment]
Gebruik van `data-vl-collapse-m`, `data-vl-collapse-s` en/of `data-vl-collapse-xs` lost dit probleem naar wens op.
